### ISSUE TITLE
Error: Failed to load image from path "/tmp/test.png" in physical iphone

### ISSUE THREAD

**Issue by Moretai** [mrousavy/react-native-jsi-image#5]
example is ok in simulator(iphone) when I add Image component to show disk uri image in screen.
however, Failed to load image from path "/tmp/test.jpg" when in physical iphone.

I try to google it, but i failed.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/19297371/167292867-990e858f-cd41-4c1f-b22f-baa44775c171.png">

**Comment by mrousavy** [comment]
That's because you're trying to write to a root domain. You compare `/test.jpg` to `/tmp/test.jpg`.
